import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/user_model.dart';
import '../models/notification_history_model.dart';
import 'notification_history_service.dart';

/// Service to check and notify users about premium expiry
class PremiumExpiryNotifier {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final NotificationHistoryService _notificationService =
      NotificationHistoryService();

  /// Check if user needs expiry warning and send notification
  Future<void> checkAndNotifyExpiry(String uid) async {
    try {
      final userDoc = await _firestore.collection('users').doc(uid).get();
      if (!userDoc.exists) return;

      final user = UserModel.fromFirestore(userDoc);

      // Only check for premium users with expiry date
      if (user.role != 'premium' || user.premiumExpiresAt == null) return;

      final now = DateTime.now();
      final expiryDate = user.premiumExpiresAt!;
      final daysUntilExpiry = expiryDate.difference(now).inDays;

      // Check if we should send warning
      String? warningType;
      if (daysUntilExpiry == 7) {
        warningType = '7_days';
      } else if (daysUntilExpiry == 3) {
        warningType = '3_days';
      } else if (daysUntilExpiry == 1) {
        warningType = '1_day';
      } else if (daysUntilExpiry == 0) {
        warningType = 'today';
      }

      if (warningType == null) return;

      // Check if we already sent this warning type today
      final todayStart = DateTime(now.year, now.month, now.day);
      final existingWarning = await _firestore
          .collection('notification_history')
          .where('userId', isEqualTo: uid)
          .where('notificationType', isEqualTo: 'premium_expiry')
          .where(
            'createdAt',
            isGreaterThanOrEqualTo: Timestamp.fromDate(todayStart),
          )
          .limit(1)
          .get();

      if (existingWarning.docs.isNotEmpty) {
        // Check if same warning type
        final existingTitle =
            existingWarning.docs.first.data()['taskTitle'] as String?;
        if (existingTitle != null &&
            (existingTitle.contains('$daysUntilExpiry day') ||
                existingTitle.contains('Today'))) {
          return; // Already sent this warning today
        }
      }

      // Send notification
      String title;
      if (daysUntilExpiry == 0) {
        title = '🚨 Premium Expires Today!';
      } else if (daysUntilExpiry == 1) {
        title = '⚠️ Premium Expires Tomorrow';
      } else {
        title = '⏰ Premium Expiring Soon';
      }

      final notification = NotificationHistoryModel(
        id: '', // Will be generated by Firestore
        userId: uid,
        taskId: 'premium_expiry_${DateTime.now().millisecondsSinceEpoch}',
        taskTitle: title,
        notificationType: 'premium_expiry',
        scheduledFor: now,
        createdAt: now,
        shown: false,
      );

      await _notificationService.createNotificationHistory(notification);

      print('✅ Sent $warningType premium expiry warning to user $uid');
    } catch (e) {
      print('❌ Error checking premium expiry: $e');
    }
  }
}
