// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk5dxEpLpaXAg_YLZFTQN9FYQkXLFUJfA',
    appId: '1:416175714950:web:a949b98796974831a7d707',
    messagingSenderId: '416175714950',
    projectId: 'cleanhnote-hironing',
    authDomain: 'cleanhnote-hironing.firebaseapp.com',
    storageBucket: 'cleanhnote-hironing.firebasestorage.app',
    measurementId: 'G-LC1GTY17XY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTVYPX38n5T-K22J0ksfbLYHvHyeswdrQ',
    appId: '1:416175714950:android:7a00e808e03d86b1a7d707',
    messagingSenderId: '416175714950',
    projectId: 'cleanhnote-hironing',
    storageBucket: 'cleanhnote-hironing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnt2Hf91hqIN4b6UUA0TvU7XWpWalRrh8',
    appId: '1:416175714950:ios:c7f4c03d59521c75a7d707',
    messagingSenderId: '416175714950',
    projectId: 'cleanhnote-hironing',
    storageBucket: 'cleanhnote-hironing.firebasestorage.app',
    androidClientId: '416175714950-1mvk2i0jmp95lacjlua0vi4a9n1btqi3.apps.googleusercontent.com',
    iosClientId: '416175714950-at8kmopp7bopq5ntf8t1v9hp75qqd4p3.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanhnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnt2Hf91hqIN4b6UUA0TvU7XWpWalRrh8',
    appId: '1:416175714950:ios:c7f4c03d59521c75a7d707',
    messagingSenderId: '416175714950',
    projectId: 'cleanhnote-hironing',
    storageBucket: 'cleanhnote-hironing.firebasestorage.app',
    androidClientId: '416175714950-1mvk2i0jmp95lacjlua0vi4a9n1btqi3.apps.googleusercontent.com',
    iosClientId: '416175714950-at8kmopp7bopq5ntf8t1v9hp75qqd4p3.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanhnote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk5dxEpLpaXAg_YLZFTQN9FYQkXLFUJfA',
    appId: '1:416175714950:web:f21db7f15281107ca7d707',
    messagingSenderId: '416175714950',
    projectId: 'cleanhnote-hironing',
    authDomain: 'cleanhnote-hironing.firebaseapp.com',
    storageBucket: 'cleanhnote-hironing.firebasestorage.app',
    measurementId: 'G-JNRN7HZGHC',
  );
}
